version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: products_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: products_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
